POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "alice.garcia@dlsu.edu.ph", 
    "password": "alicePass123"
}

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": {
    "first_name": "Sample",
    "last_name": "Sample"
    },
    "email": "sample@dlsu.edu.ph",
    "password": "sample",
    "bio": ""
}