GET http://localhost:3000/users

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "clark_kent@dlsu.edu.ph",
  "password": "superman123"
}

###

PUT http://localhost:3000/hash
Content-Type: application/json

{
  "id": "688e3383b0d8ab34b7c22b9b",
  "password": "superman123"
}