GET http://localhost:3000/users

###
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "idNumber": "12345678",
  "firstName": "Sample",
  "lastName": "Sample",
  "role": "student",
  "email": "sample@dlsu.edu.ph",
  "password": "sample1234"
}